type Runtime = import("@astrojs/cloudflare").Runtime<Env>;

declare namespace App {
  interface Locals extends Runtime {}
}

// worker-configuration.d.ts is regenerated by `wrangler types` and only knows
// about bindings declared in wrangler.json, so the Stripe secret (set via
// `wrangler secret put STRIPE_SECRET_KEY` / a local .dev.vars file) is added
// here instead. This merges into the same global `Env` interface.
interface Env {
  STRIPE_SECRET_KEY: string;
}
